---
- name: Setup React App Directory and Clone Repo
  hosts: "{{ _hosts | default(omi) }}"
  become: true
  vars:
    target_dir: "~/mcaDemo"
    repo_url: "https://github.com/ddoan30/reactapp-dev.git"

  tasks:
    - name: Ensure 'git' is installed on host
      ansible.builtin.dnf: 
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: Ensure the directory "mcaDemo" exists in the home directory
      ansible.builtin.file:
        path: "{{ target_dir }}"
        state: directory
        mode: '0755'
        owner: "ec2-user"
        group: "ec2-user"

    - name: Clone the React app repository into mcaDemo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ target_dir }}"
        version: main  # Change this if the default branch is different (e.g., master)
        force: yes     # Overwrites local changes if they exist
      become_user: "ec2-user"
